<?php
// Actual complete card POST parsing/dispatch after shared session bootstrap,
// native driver and canonical isolated schema. Never use live accounts/bans.
if(PHP_SAPI!=='cli'||getenv('PHPBB_CARD_NATIVE')!=='1'){echo "Native moderation cards require explicitly enabled disposable storage.\n";return;}
if(!in_array('mail',array_map('trim',explode(',',ini_get('disable_functions'))),true)){throw new RuntimeException('Native fixture requires -d disable_functions=mail; never send test messages');}
putenv('PHPBB_LOGIN_PUBLICATION_NATIVE=1');putenv('PHPBB_LOGIN_PUBLICATION_PORT='.(getenv('PHPBB_CARD_PORT')?:'3306'));putenv('PHPBB_LOGIN_PUBLICATION_PASSWORD='.(getenv('PHPBB_CARD_PASSWORD')?:''));
$source=file_get_contents(__DIR__.'/check-login-publication-native.php');$cut=strpos($source,"\ntry{\n set_error_handler");if($cut===false){throw new RuntimeException('Shared native fixture boundary');}
eval(substr(str_replace('__DIR__',var_export(__DIR__,true),substr($source,0,$cut)),5));
foreach(array('MOD'=>2,'USER'=>0,'POST_USERS_URL'=>'u','POST_POST_URL'=>'p','GROUPS_TABLE'=>'fixture_groups','USER_GROUP_TABLE'=>'fixture_user_group','AUTH_ACCESS_TABLE'=>'fixture_auth_access','FORUMS_TABLE'=>'fixture_forums','POSTS_TABLE'=>'fixture_posts','TOPICS_TABLE'=>'fixture_topics')as$key=>$value){define($key,$value);}
preg_match_all("/define\('(AUTH_[A-Z_]+)', ([0-9]+)\);/",file_get_contents($ats_source.'includes/constants.php'),$constants,PREG_SET_ORDER);foreach($constants as$c){if(!defined($c[1])){define($c[1],(int)$c[2]);}}
require $ats_source.'includes/functions_card_storage.php';
$controller=file_get_contents($ats_source.'card.php');$start=strpos($controller,'// Find exactly one submitted card action.');$bootstrap=strpos($controller,'$userdata = session_pagestart',$start);$after=strpos($controller,'init_userprefs($userdata);',$bootstrap);$end=strpos($controller,'$bluecard_limit = max(1,',$after);
ats_check($start!==false&&$bootstrap>$start&&$after>$bootstrap&&$end>$after,'Complete actual moderation controller boundaries');
$card_body=substr($controller,$start,$bootstrap-$start).substr($controller,$after+strlen('init_userprefs($userdata);'),$end-$after-strlen('init_userprefs($userdata);'));
function card_reset($actor='admin',$setup=null){
 global $lp_open,$lp_owner_queries,$lp_query_count,$lp_failure,$lp_hook,$lp_after_commit,$lp_committed,$lp_commit_failure,$lp_reuse,$db,$main,$userdata,$board_config,$user_ip;
 ats_check($lp_open===0,'Prior card owner released');$lp_owner_queries=array();$lp_query_count=$lp_failure=0;$lp_hook=$lp_after_commit=null;$lp_committed=$lp_reuse=false;$lp_commit_failure='';
 foreach(array('users','sessions','sessions_keys','banlist','config','groups','user_group','auth_access','forums','posts','topics')as$table){lp_query('DELETE FROM fixture_'.$table);}
 foreach(array(-1,1,2,3)as$id){lp_insert('fixture_users',array('user_id'=>$id,'username'=>'Fixture '.$id,'user_level'=>$id===1?($actor==='admin'?ADMIN:MOD):USER,'user_active'=>1,'user_blocktime'=>0,'user_warnings'=>$id===2?9:0,'user_email'=>'','user_lang'=>'english'));}
 foreach(array('actor'=>1,'target'=>2,'other'=>3)as$name=>$id){lp_insert('fixture_sessions',array('session_id'=>'fixture-'.$name,'session_user_id'=>$id,'session_logged_in'=>1,'session_admin'=>0,'session_ip'=>$id===1?'0a000001':'7f000001'));}
 lp_insert('fixture_sessions_keys',array('user_id'=>2,'key_id'=>str_repeat('a',32)));
 lp_insert('fixture_config',array('config_name'=>'max_user_bancard','config_value'=>'10'));lp_insert('fixture_config',array('config_name'=>'block_time','config_value'=>'15'));
 lp_insert('fixture_config',array('config_name'=>'board_disable','config_value'=>'0'));
 lp_insert('fixture_groups',array('group_id'=>10,'group_name'=>'Real moderation group','group_single_user'=>0));
 lp_insert('fixture_user_group',array('user_id'=>1,'group_id'=>10,'user_pending'=>0));lp_insert('fixture_auth_access',array('group_id'=>10,'forum_id'=>20,'auth_mod'=>1));
 lp_insert('fixture_forums',array('forum_id'=>20,'auth_view'=>AUTH_ALL,'auth_read'=>AUTH_ALL,'auth_ban'=>AUTH_MOD,'auth_greencard'=>AUTH_MOD));
 lp_insert('fixture_topics',array('topic_id'=>40,'forum_id'=>20,'topic_moved_id'=>0));
 lp_insert('fixture_posts',array('post_id'=>30,'poster_id'=>2,'forum_id'=>20,'topic_id'=>40));
 $db=$main;$userdata=array('user_id'=>1,'session_id'=>'fixture-actor','session_logged_in'=>1,'user_level'=>ADMIN,'session_admin'=>1);
 $board_config=array('board_disable'=>0,'max_user_bancard'=>99,'block_time'=>99,'default_lang'=>'english','smtp_delivery'=>0,'board_email'=>'board@example.invalid','sitename'=>'Fixture','board_email_sig'=>'Fixture','server_name'=>'example.invalid','server_port'=>80,'script_path'=>'/','cookie_secure'=>0);$user_ip='0a000001';
 if($setup!==null){call_user_func($setup);}
}
function card_run($action,$options=array()){
 global $card_body,$db,$userdata,$user_ip,$lang,$phpbb_root_path,$phpEx,$board_config;
 $request=array($action.'_x'=>'1','sid'=>'fixture-actor','post_id'=>'30');if(isset($options['request'])){$request=array_merge($request,$options['request']);}if(!empty($options['user_mode'])){unset($request['post_id']);$request['u']='2';}
 profile_fixture_request($request);$_SERVER['REQUEST_METHOD']=isset($options['method'])?$options['method']:'POST';
 $GLOBALS['card_run_started']=time();
 try{eval($card_body);throw new RuntimeException('Actual moderation controller must terminate');}catch(AttachSettingsExit $e){$GLOBALS['card_run_finished']=time();ats_check($GLOBALS['lp_open']===0&&$db===$GLOBALS['main'],'Card response only after owner release, caller unchanged');return $e->getMessage();}
}
function card_success($out){foreach(array('Ban_update_red','Ban_update_green','Ban_update_yellow','Block_update','user_already_banned')as$key){$prefix=strtok($GLOBALS['lang'][$key],'%');if(strpos($out,$prefix)===0){return true;}}return false;}
function card_rows($sql){$rows=lp_rows($sql);foreach($rows as$i=>$row){foreach($row as$key=>$value){if(is_int($key)){unset($rows[$i][$key]);}}}return $rows;}
function card_snapshot(){return array(card_rows('SELECT ban_userid,ban_ip,ban_email,ban_ip_mask FROM fixture_banlist ORDER BY ban_id'),card_rows('SELECT user_id,user_warnings,user_block_by,user_blocktime FROM fixture_users ORDER BY user_id'),card_rows('SELECT session_id,session_user_id,session_logged_in,session_admin FROM fixture_sessions ORDER BY session_id'),card_rows('SELECT user_id,key_id FROM fixture_sessions_keys ORDER BY user_id,key_id'));}
function card_durable_matches($expected,$action){
 $actual=card_snapshot();
 if($action==='block'){foreach($actual[1]as$i=>$user){if((int)$user['user_id']===2){ats_check((int)$user['user_blocktime']>=$GLOBALS['card_run_started']+900&&(int)$user['user_blocktime']<=$GLOBALS['card_run_finished']+900,'Committed block deadline lies inside actual action interval plus configured15 minutes');$expected[1][$i]['user_blocktime']=$user['user_blocktime'];}}}
 return $actual===$expected;
}
$cases=$serialized=0;
try{
 set_error_handler(function($s,$m){if(error_reporting()&$s){throw new RuntimeException($m);}});
 $schema=file_get_contents($ats_source.'install/schemas/mysql_schema.sql');foreach(array('users','sessions','sessions_keys','banlist','config','groups','user_group','auth_access','forums','posts','topics')as$table){ats_check(preg_match('/CREATE TABLE `?phpbb_'.$table.'`?\s*\([\s\S]*?;/',$schema,$m)===1,'Canonical card participant');lp_query(str_replace('phpbb_'.$table,'fixture_'.$table,$m[0]));}
 foreach(array('','STRICT_ALL_TABLES','ANSI_QUOTES','NO_BACKSLASH_ESCAPES')as$mode){$main->sql_query("SET SESSION sql_mode='$mode'");lp_query("SET SESSION sql_mode='$mode'");foreach(array('admin','moderator')as$actor){foreach(array('ban','warn','unban','block')as$action){
  card_reset($actor);ats_check(card_success(card_run($action)),'Actual authorized '.$mode.'/'.$actor.'/'.$action);
  $u=lp_rows('SELECT user_warnings,user_blocktime FROM fixture_users WHERE user_id=2')[0];$ban=lp_rows('SELECT ban_userid FROM fixture_banlist WHERE ban_userid=2');
  ats_check((int)$u['user_warnings']===($action==='unban'?0:($action==='block'?9:10)),'Current warning policy, not cached99');
  ats_check((bool)$ban===in_array($action,array('ban','warn'),true),'Ban and warning threshold publish together');
  ats_check(count(lp_rows('SELECT session_id FROM fixture_sessions WHERE session_user_id=2'))===($action==='unban'?1:0),'Sessions invalidated with ban/block');
  ats_check(count(lp_rows('SELECT key_id FROM fixture_sessions_keys WHERE user_id=2'))===($action==='unban'?1:0),'Autologin capabilities invalidated with ban/block');
  ats_check((int)$u['user_blocktime']===0||((int)$u['user_blocktime']>=$GLOBALS['card_run_started']+900&&(int)$u['user_blocktime']<=$GLOBALS['card_run_finished']+900),'Block uses current15 minutes within actual action interval');$cases++;
 }}}
 foreach(array('admin','moderator')as$actor){foreach(array('ban','warn','unban','block')as$action){
  $setup=$action==='unban'?function(){lp_insert('fixture_banlist',array('ban_userid'=>2,'ban_ip'=>'7f0000ff','ban_ip_mask'=>'ffffffff','ban_email'=>'keep@example.invalid'));lp_insert('fixture_banlist',array('ban_userid'=>2));}:null;
  card_reset($actor,$setup);ats_check(card_success(card_run($action)),'Record complete owner publication');$total=$lp_query_count;$expected=card_snapshot();
  for($at=1;$at<=$total;$at++){card_reset($actor,$setup);$before=card_snapshot();$lp_failure=$at;ats_check(!card_success(card_run($action))&&card_snapshot()===$before,'Every owned query failure rolls back full '.$actor.'/'.$action.'/'.$at);$cases++;}
  foreach(array('before','ack')as$failure){card_reset($actor,$setup);$before=card_snapshot();$lp_commit_failure=$failure;ats_check(!card_success(card_run($action)),'Failed/uncertain commit no success');ats_check($failure==='before'?card_snapshot()===$before:card_durable_matches($expected,$action),'Truthful commit uncertainty '.$actor.'/'.$action.'/'.$failure);$cases++;}
 }}
 foreach(array('active'=>'UPDATE fixture_users SET user_active=0 WHERE user_id=1','session'=>"DELETE FROM fixture_sessions WHERE session_id='fixture-actor'",'case'=>"UPDATE fixture_sessions SET session_id='FIXTURE-ACTOR' WHERE session_id='fixture-actor'",'logout'=>"UPDATE fixture_sessions SET session_logged_in=0 WHERE session_id='fixture-actor'",'foreign'=>"UPDATE fixture_sessions SET session_user_id=3 WHERE session_id='fixture-actor'",'membership'=>'DELETE FROM fixture_user_group WHERE user_id=1','pending'=>'UPDATE fixture_user_group SET user_pending=1 WHERE user_id=1','orphan'=>'DELETE FROM fixture_groups WHERE group_id=10','acl'=>'DELETE FROM fixture_auth_access WHERE forum_id=20','forum'=>'DELETE FROM fixture_forums WHERE forum_id=20','post'=>'DELETE FROM fixture_posts WHERE post_id=30','hidden'=>'UPDATE fixture_forums SET auth_read=5 WHERE forum_id=20','target-admin'=>'UPDATE fixture_users SET user_level=1 WHERE user_id=2','target-gone'=>'DELETE FROM fixture_users WHERE user_id=2','policy'=>"DELETE FROM fixture_config WHERE config_name='max_user_bancard'")as$kind=>$sql){
  card_reset('moderator');lp_query($sql);$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&card_snapshot()===$before,'Stale cached authority/current target refuses '.$kind);$cases++;
 }
 card_reset('admin');lp_query('UPDATE fixture_forums SET auth_ban=5 WHERE forum_id=20');lp_query('UPDATE fixture_users SET user_level=0 WHERE user_id=1');$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&card_snapshot()===$before,'Revoked current admin cannot use stale admin cache');$cases++;
 foreach(array('board-disabled'=>"UPDATE fixture_config SET config_value='1' WHERE config_name='board_disable'",'board-policy-missing'=>"DELETE FROM fixture_config WHERE config_name='board_disable'",'topic-gone'=>'DELETE FROM fixture_topics WHERE topic_id=40','topic-foreign'=>'UPDATE fixture_topics SET forum_id=21 WHERE topic_id=40','topic-shadow'=>'UPDATE fixture_topics SET topic_moved_id=99 WHERE topic_id=40','pending-null'=>'UPDATE fixture_user_group SET user_pending=NULL WHERE user_id=1')as$kind=>$sql){card_reset('moderator');lp_query($sql);$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&card_snapshot()===$before,'Complete current context refuses '.$kind);$cases++;}
 card_reset('admin');lp_insert('fixture_user_group',array('group_id'=>0,'user_id'=>1,'user_pending'=>0));ats_check(card_success(card_run('ban')),'Unrelated invalid membership cannot disable real root authority');$cases++;
 card_reset('moderator');lp_query('DELETE FROM fixture_user_group WHERE user_id=1');lp_insert('fixture_user_group',array('group_id'=>0,'user_id'=>1,'user_pending'=>0));$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&card_snapshot()===$before,'Invalid-only membership cannot grant moderation');$cases++;
 foreach(array(AUTH_ALL,AUTH_REG,AUTH_ACL,AUTH_MOD,AUTH_ADMIN)as$permission){card_reset('moderator');lp_query('UPDATE fixture_forums SET auth_ban='.$permission.' WHERE forum_id=20');if($permission===AUTH_ACL){lp_query('UPDATE fixture_auth_access SET auth_mod=0,auth_ban=1 WHERE forum_id=20');}$before=card_snapshot();$ok=card_success(card_run('ban'));ats_check($ok===($permission!==AUTH_ADMIN),'Current explicit forum policy follows actual ACL semantics');if(!$ok){ats_check(card_snapshot()===$before,'Unmet explicit policy unchanged');}$cases++;}
 foreach(array('self'=>"UPDATE fixture_posts SET poster_id=1 WHERE post_id=30",'blocked'=>"UPDATE fixture_users SET user_blocktime=".(time()+3600).' WHERE user_id=1','actor-banned'=>"INSERT INTO fixture_banlist(ban_userid,ban_ip,ban_email)VALUES(1,'','')",'corrupt-mask'=>"INSERT INTO fixture_banlist(ban_userid,ban_ip,ban_email,ban_ip_mask)VALUES(0,'7f000001','','invalid!')",'bad-warning'=>"UPDATE fixture_config SET config_value='32768' WHERE config_name='max_user_bancard'")as$kind=>$sql){card_reset();lp_query($sql);$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&card_snapshot()===$before,'Refuse '.$kind.' without partial effects');$cases++;}
 foreach(array('missing'=>"DELETE FROM fixture_config WHERE config_name='block_time'",'negative'=>"UPDATE fixture_config SET config_value='-1' WHERE config_name='block_time'",'overflow'=>"UPDATE fixture_config SET config_value='99999999' WHERE config_name='block_time'")as$kind=>$sql){card_reset();lp_query($sql);$before=card_snapshot();ats_check(!card_success(card_run('block'))&&card_snapshot()===$before,'Refuse invalid current block policy '.$kind);$cases++;}
 card_reset();lp_query('UPDATE fixture_users SET user_warnings=32767 WHERE user_id=2');ats_check(card_success(card_run('warn'))&&(int)lp_rows('SELECT user_warnings FROM fixture_users WHERE user_id=2')[0]['user_warnings']===32767,'Warning counter saturates without strict overflow while ban publishes');$cases++;
 card_reset();lp_query('UPDATE fixture_users SET user_active=0 WHERE user_id=2');ats_check(card_success(card_run('unban'))&&(int)lp_rows('SELECT user_active FROM fixture_users WHERE user_id=2')[0]['user_active']===0,'User unban does not reactivate separately disabled accounts');$cases++;
 foreach(array(array('method'=>'GET'),array('request'=>array('sid'=>'other')),array('request'=>array('post_id'=>'30x')),array('request'=>array('post_id'=>'16777216')),array('request'=>array('post_id'=>array('30'))),array('request'=>array('warn_x'=>'1')),array('request'=>array('u'=>'3')),array('request'=>array('ban_x'=>array('1'))))as$options){card_reset();$before=card_snapshot();ats_check(!card_success(card_run('ban',$options))&&card_snapshot()===$before,'Invalid whole POST has no effects');$cases++;}
 foreach(array('admin','moderator')as$actor){card_reset($actor);$before=card_snapshot();ats_check(card_success(card_run('ban',array('user_mode'=>true)))===($actor==='admin'),'Outside-forum user-mode is current ADMIN only');if($actor!=='admin'){ats_check(card_snapshot()===$before,'Moderator user-mode unchanged');}$cases++;}
 card_reset();lp_query('UPDATE fixture_users SET user_warnings=NULL WHERE user_id=2');ats_check(card_success(card_run('warn'))&&(int)lp_rows('SELECT user_warnings FROM fixture_users WHERE user_id=2')[0]['user_warnings']===1,'Historical NULL warning count becomes one');$cases++;
 card_reset();lp_insert('fixture_banlist',array('ban_userid'=>2,'ban_ip'=>'7f0000ff','ban_ip_mask'=>'ffffffff','ban_email'=>'keep@example.invalid'));ats_check(card_success(card_run('unban'))&&card_rows('SELECT ban_userid,ban_ip,ban_ip_mask,ban_email FROM fixture_banlist')===array(array('ban_userid'=>'0','ban_ip'=>'7f0000ff','ban_ip_mask'=>'ffffffff','ban_email'=>'keep@example.invalid')),'Combined independent IP/mask/email retained byte-exact');$cases++;
 card_reset();ats_check(card_success(card_run('ban'))&&card_success(card_run('ban'))&&count(lp_rows('SELECT ban_id FROM fixture_banlist WHERE ban_userid=2'))===1,'Repeated ban no duplicate/undefined mail template');$cases++;
 foreach(array('before','ack','ok')as$commit){card_reset();lp_query("UPDATE fixture_users SET user_email='member@example.invalid' WHERE user_id=2");$lp_commit_failure=$commit==='ok'?'':$commit;$before=card_snapshot();
  if($commit==='ok'){$seen=false;$lp_after_commit=function()use(&$seen){$seen=true;ats_check(!class_exists('emailer',false),'Mailer not loaded before confirmed commit');};}
  $out=card_run('warn');ats_check(card_success($out)===($commit==='ok'),'Mail cannot turn failed/uncertain commit into success');
  if($commit==='ok'){ats_check($seen&&strpos($out,$lang['Card_notification_failed'])!==false&&count(lp_rows('SELECT ban_id FROM fixture_banlist WHERE ban_userid=2'))===1,'Actual disabled transport failure reported AFTER durable ban, no rollback');}elseif($commit==='before'){ats_check(card_snapshot()===$before,'Pre-commit failure does not deliver or save notification');}else{ats_check(count(lp_rows('SELECT ban_id FROM fixture_banlist WHERE ban_userid=2'))===1,'Uncertain acknowledged state is durable without email/success');}$cases++;
 }
 card_reset();$before=card_snapshot();$seen=false;$lp_hook=function($sql,$connection)use(&$seen){if($seen||strpos($sql,'INSERT INTO fixture_banlist')!==0){return;}$seen=true;$GLOBALS['lp_hook']=null;lp_query('KILL CONNECTION '.mysqli_thread_id($connection->db_connect_id));};ats_check(!card_success(card_run('warn'))&&$seen&&card_snapshot()===$before,'Lost owning connection cannot publish warning or ban');$cases++;
 foreach(array('role'=>'UPDATE fixture_users SET user_level=0 WHERE user_id=1','active'=>'UPDATE fixture_users SET user_active=0 WHERE user_id=1','session'=>"DELETE FROM fixture_sessions WHERE session_id='fixture-actor'",'policy'=>"UPDATE fixture_config SET config_value='20' WHERE config_name='max_user_bancard'",'group'=>'DELETE FROM fixture_groups WHERE group_id=10','membership'=>'DELETE FROM fixture_user_group WHERE user_id=1','acl'=>'DELETE FROM fixture_auth_access WHERE forum_id=20','post'=>'UPDATE fixture_posts SET poster_id=3 WHERE post_id=30','forum'=>'UPDATE fixture_forums SET auth_ban=5 WHERE forum_id=20','target'=>'UPDATE fixture_users SET user_level=1 WHERE user_id=2','rules'=>"INSERT INTO fixture_banlist(ban_userid,ban_ip,ban_email)VALUES(0,'','independent@example.invalid')",'ddl'=>'ALTER TABLE fixture_banlist ENGINE=MyISAM')as$kind=>$sql){
  card_reset('moderator');$seen=$blocked=false;$lp_hook=function($query)use($sql,&$seen,&$blocked){if($query!=='COMMIT'||$seen){return;}$seen=true;$GLOBALS['lp_hook']=null;lp_query('SET SESSION innodb_lock_wait_timeout=0');lp_query('SET SESSION lock_wait_timeout=0');try{$r=$GLOBALS['peer']->sql_query($sql);$e=$GLOBALS['peer']->sql_error();ats_check(!$r&&(int)$e['code']===1205,'Actual concurrent change is blocked through commit');$blocked=true;}finally{lp_query('SET SESSION innodb_lock_wait_timeout=1');lp_query('SET SESSION lock_wait_timeout=1');}};
  ats_check(card_success(card_run('warn'))&&$seen&&$blocked,'Serialized '.$kind);$cases++;$serialized++;
 }
 foreach(array('users','sessions','sessions_keys','banlist','config','groups','user_group','auth_access','forums','posts','topics')as$table){foreach(array('ENGINE=MyISAM','ROW_FORMAT=COMPACT','CONVERT TO CHARACTER SET latin1')as$legacy){card_reset();lp_query('SET SESSION innodb_strict_mode=OFF');try{lp_query('ALTER TABLE fixture_'.$table.' '.$legacy);}finally{lp_query('SET SESSION innodb_strict_mode=ON');}$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&card_snapshot()===$before,'Legacy participant refused');lp_query('ALTER TABLE fixture_'.$table.' ENGINE=InnoDB ROW_FORMAT=DYNAMIC, CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');$cases++;}}
 foreach(array('board-disable'=>"UPDATE fixture_config SET config_value='1' WHERE config_name='board_disable'",'topic-move'=>'UPDATE fixture_topics SET forum_id=21 WHERE topic_id=40','topic-shadow'=>'UPDATE fixture_topics SET topic_moved_id=99 WHERE topic_id=40')as$kind=>$sql){
  card_reset('moderator');$seen=$blocked=false;$lp_hook=function($query)use($sql,&$seen,&$blocked){if($query!=='COMMIT'||$seen){return;}$seen=true;$GLOBALS['lp_hook']=null;lp_query('SET SESSION innodb_lock_wait_timeout=0');lp_query('SET SESSION lock_wait_timeout=0');try{$r=$GLOBALS['peer']->sql_query($sql);$e=$GLOBALS['peer']->sql_error();ats_check(!$r&&(int)$e['code']===1205,'Current whole-topic/board context locked through commit');$blocked=true;}finally{lp_query('SET SESSION innodb_lock_wait_timeout=1');lp_query('SET SESSION lock_wait_timeout=1');}};
  ats_check(card_success(card_run('ban'))&&$seen&&$blocked,'Serialized whole context '.$kind);$cases++;$serialized++;
 }
 lp_query('CREATE TABLE fixture_caller(marker INT PRIMARY KEY)ENGINE=InnoDB ROW_FORMAT=DYNAMIC');card_reset();$main->sql_query('START TRANSACTION');$lp_fixture_write=true;$main->sql_query('INSERT INTO fixture_caller VALUES(1)');$lp_fixture_write=false;ats_check(card_success(card_run('ban'))&&lp_rows('SELECT * FROM fixture_caller')===array(),'Cannot commit caller transaction');$main->sql_query('ROLLBACK');$cases++;
 card_reset();$main->sql_query('START TRANSACTION');$lp_fixture_write=true;$main->sql_query('INSERT INTO fixture_caller VALUES(2)');$lp_fixture_write=false;$lp_reuse=true;$before=card_snapshot();ats_check(!card_success(card_run('ban'))&&$main->db_connect_id!==null&&card_snapshot()===$before&&lp_rows('SELECT * FROM fixture_caller')===array(),'Reused factory cannot commit/close caller');$main->sql_query('ROLLBACK');$cases++;
 echo 'Native actual moderation cards: '.$cases.' boundary/failure cases and '.$serialized." serialized changes passed.\n";
}finally{$main->sql_close();$peer->sql_close();$control->sql_query('DROP DATABASE '.$fixture);$control->sql_close();restore_error_handler();}
