<?php
// Persistent defaults for the bundled Mod Settings registry, including hidden
// counters and user-override flags. Existing installation values always win.
// CI compares these with the actual registry and fresh-install SQL seed.
return array(
	'announcement_date_display' => '1',
	'announcement_date_display_over' => '0',
	'announcement_display' => '1',
	'announcement_display_forum' => '1',
	'announcement_display_forum_over' => '0',
	'announcement_display_over' => '0',
	'announcement_duration' => '7',
	'announcement_forum' => '1',
	'announcement_forum_over' => '0',
	'announcement_prune_strategy' => '0',
	'announcement_split' => '1',
	'announcement_split_over' => '0',
	'calendar_birthday' => '1',
	'calendar_birthday_over' => '0',
	'calendar_display_open' => '0',
	'calendar_display_open_over' => '0',
	'calendar_forum' => '1',
	'calendar_forum_over' => '0',
	'calendar_header_cells' => '7',
	'calendar_header_cells_over' => '0',
	'calendar_nb_row' => '5',
	'calendar_nb_row_over' => '0',
	'calendar_text_length' => '200',
	'calendar_title_length' => '30',
	'calendar_week_start' => '1',
	'calendar_week_start_over' => '0',
	'display_viewonline' => '2',
	'display_viewonline_over' => '0',
	'icon_per_row' => '10',
	'last_topic_title' => '1',
	'last_topic_title_length' => '24',
	'last_topic_title_over' => '0',
	'max_posts' => '0',
	'max_topics' => '0',
	'max_users' => '0',
	'split_announce' => '1',
	'split_announce_over' => '0',
	'split_cat' => '1',
	'split_cat_over' => '0',
	'split_global_announce' => '1',
	'split_global_announce_over' => '0',
	'split_news' => '1',
	'split_news_over' => '0',
	'split_sticky' => '1',
	'split_sticky_over' => '0',
	'split_topic_split' => '0',
	'split_topic_split_over' => '0',
	'sub_forum' => '1',
	'sub_forum_over' => '0',
	'sub_level_links' => '2',
	'sub_level_links_over' => '0',
	'use_ajax_edit' => '1',
	'use_ajax_edit_over' => '0',
	'use_ajax_preview' => '1',
	'use_ajax_preview_over' => '0',
);
